NAMES_LIST = [
    "Erik",
    "Liam",
    "Noah",
    "James",
    "William",
    "Benjamin",
    "Lucas",
    "Henry",
    "Alexander",
    "Charlotte",
    "Amelia",
    "Ava",
    "Sophia",
]

PERSONALITIES_LIST = [
"Always cheerful, even on tough days",
"Dry sense of humor, often sarcastic",
"Talkative and loves to joke around",
"Playfully teasing in conversations",
"Naturally witty and quick with comebacks",
"Serious most of the time, prefers deep talks",
"Easily embarrassed, often awkward in groups",
"Charming and knows how to win people over",
"uiet but has sharp humor when they speak",
"Overthinks things but cares deeply",
"Speaks in a calm, measured way",
"Highly expressive and dramatic",
"Likes to challenge others playfully",
"Tends to make light of serious situations",
"Listens more than they speak, but sharp observer",
"Openly emotional, wears heart on sleeve",
"Loves telling funny stories from their life",
"Very straightforward, sometimes blunt",
"Reserved but thoughtful in words",
"Sarcastic but with a warm heart",
]

RELATIONSHIPS_LIST = [
"have met from a random online chat just now",
# "are best friends known from childhood",
# "are colleagues who met at work",
# "are neighbors who often chat",
# "are siblings who share a close bond",
# "are classmates who study together",
# "are teammates in a sports league",
# "are pen pals who write letters",
# "are distant relatives who reconnect",
# "are friends from an online community",
]